export const books=[
        {
        name:"The-Art-of-War",
        author:"Sun Tzu",
        quotes:[
          '"There is no instance of country having benefited from prolonged warfare."',
        '"It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can no account be neglected."',
        '"The supreme art of war is to subdue the enemy without fighting."',
        '"He will win who knows when to fight when not to fight."',
        '"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win."',
        '"If you focus everywhere, you will be weak everywhere."',
        '"All warfare is based on deception."',
        '"In the middle of chaos, there is always an opportunity."',
        '"Know yourself , know your enemy. A thousand battles, a thousand victories."',
        '"Opportunities multiply, when you take the advantage of them."',
        '"The greatest victory is that which requires no battle."',
        '"The battle is won in the mind long before it is won on the field."',
        '"When your army has crossed the border, you should burn your boats and bridges, in order to make it clear to everybody that you have no hankering after home."',
        '"Your can hesitations lead you to disaster. "',
        '"Ponder and deliberate before you make a move. "',
        '"The expert in battle move the enemy, and is not moved by them. "',
        '"Appear weak when you are strong and weak when you are strong. All Warfare is about deception."',
         '"Even the finest sword get rusted because of salt water."',
         '"Be like a two headed snake.No matter from where the enemy attacks, you will counter from another angle."',
         '"Great success can be achieved with small steps."',
         '"if you want to fight, first count the cost of it."',
         '"Let your plans be dark as night,and when you move fall like a thunderbolt."',
         '"He will win who knows how to handle both superior & inferior forces."',
         '"The wise warrior avoids the battle."',
         '"Do not repeat the tactics which have gained you one victory, but let your methods be regulated by the infinite variety of circumstances."',
         '"Water adjust its form according to the nature of the ground over which it flows, the soldier should also adjust his tactics in relation to the foe whom he is facing."'
        ]
        },
        {
        name:"The-laws-of-human-nature",
        author:"Robert Greene",
        quotes : [
    "The deepest need of human nature is the desire to be appreciated.",
    "We are all actors in our own lives, and we must learn to see through the masks that others wear.",
    "The greatest power you can possess is the ability to control your own emotions.",
    "People are rarely what they seem. We must learn to look beneath the surface and see their true nature.",
    "The key to understanding human behavior is to recognize the power of emotions.",
    "We are all driven by unconscious desires and motivations that we are not even aware of.",
    "To truly understand others, we must first understand ourselves.",
    "The more you try to control people, the more they will resist you.",
    "The best way to influence others is to appeal to their self-interest.",
    "The world is full of people who are trying to deceive you. You must learn to see through their lies.",
    "Never be intimidated by the surface. The most complex and cunning people mask themselves in simplicity.",
    "The human animal is a social creature. We are deeply influenced by the groups we belong to and the people around us.",
    "Most people are emotionally driven, not rational. Understanding this is key to influencing them.",
    "We are all prone to illusions and biases. The first step to wisdom is recognizing this.",
    "The shadow self is the darker side of your personality. Ignoring it doesn't make it go away; it makes it stronger.",
    "Empathy is not simply feeling what others feel. It's understanding their perspective, their motivations.",
    "People rarely change. Accept this and adjust your expectations accordingly.",
    "The desire for power is a fundamental human drive. Learn to recognize it in yourself and others.",
    "Behind everyone's mask is a story, a set of experiences that have shaped them. Try to understand that story.",
    "Self-awareness is the foundation of wisdom. Know thyself before trying to understand others.",
    "Beware of people who praise you too much. They might be trying to trick you into doing something for them.",
    "We are all actors on a stage, playing roles we have been assigned or have chosen for ourselves.",
    "The need to belong is a fundamental human drive, shaping our actions and beliefs.",
    "Conformity is a powerful social force; we often mirror those around us to gain acceptance.",
    "True understanding comes from looking beyond outward appearances and considering inner motivations.",
    "Unacknowledged emotions can sabotage our best intentions and lead to destructive behavior.",
    "Personal growth begins with the courage to confront our own flaws and inconsistencies.",
    "Influence is often achieved not through force, but through understanding and appealing to others' needs.",
    "Skepticism, when balanced with trust, is a valuable tool for navigating social interactions.",
    "Our past experiences cast long shadows, shaping our present behavior in ways we may not realize."
]

        },
        {name:"48-Laws-of-Power",
          author:"Robert Greene",
          quotes:["Law 1: Never Outshine Your Master","Law 2 : ","Law 3","Law 4"]
        }
        ]
  